# Google Cloud Build script
#

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/airflow-operator/airflow:1.10.12', '.']
images: ['gcr.io/airflow-operator/airflow:1.10.12']
